spring.application.name=ai-plan
spring.main.web-application-type=none
spring.ai.google.genai.chat.options.model=gemini-2.5-flash
spring.ai.google.genai.embedding.text.options.model=gemini-embedding-001
spring.ai.google.genai.embedding.api-key=${spring.ai.google.genai.api-key}
# set spring.ai.google.genai.api-key in application-default.properties (gitignored)
